### ISSUE TITLE
rename partition name to 'pis' not my cluster also add option to set the partition name from commsndline

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-slurm#12]
rename cluster name to name of manager

**Comment by jpfleischer** [comment]
we have decided to call the partition 'default'.

**Comment by jpfleischer** [comment]
this breaks slurm.
proof: https://www.mail-archive.com/slurm-dev@schedmd.com/msg08392.html
we have reverted it back to mycluster.

**Comment by laszewsk** [comment]
lets try to rename "pis" and be able to specify the name in some fashion with an option
--partition="pis"
[deafult: pis]

**Comment by jpfleischer** [comment]
this has been resolved with https://github.com/cloudmesh/cloudmesh-slurm/commit/fa32dc6705b28f3539b41c76f0059d53916b3d50
