### ISSUE TITLE
1: use now the pi nfs command

### ISSUE THREAD

**Issue by jpfleischer** [cloudmesh/cloudmesh-slurm#6]
right now nfs is manual but we need to integrate the new pi nfs

**Comment by jpfleischer** [comment]
this has been integrated. i want to comment that most of the step 2 within the slurm installation is now out-commented. i am not sure if i should leave that entire section within the script while it is out-commented, or just delete it.

**Comment by jpfleischer** [comment]
here is the script. https://github.com/cloudmesh/cloudmesh-slurm/blob/main/cloudmesh/slurm/slurm.py

**Comment by laszewsk** [comment]
please see comments in script. You may like the comments.
especially my proposal for the script_executor, making this prg more readable ;-)

**Comment by laszewsk** [comment]
can you send me url to pi nfs command
i reviewed slurm.py and made some suggestions
